import type { Metadata } from "next";
import "./globals.css";
import { PersonalInfoProvider } from "@/lib/context/PersonalDataContext";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
      >   
        <PersonalInfoProvider>
          {children}
        </PersonalInfoProvider>

      </body>
    </html>
    </ClerkProvider>
  );
}
